---
- name: Install Docker
  hosts: docker_server
  become: yes
  tasks:
    - name: Make sure Docker is installed
      yum:
        name: docker
        update_cache: yes
        state: present
    - name: Ensure Docker is running
      systemd:
        name: docker
        state: started
  
- name: Install docker-compose
  hosts: docker_server
  tasks:
    - name: Create docker-compose directory
      file:
        path: ~/.docker/cli-plugins
        state: directory
    - name: Get architecture of remote machine
      shell: uname -m
      register: remote_arch
    - name: Download and install docker-compose
      get_url: 
        url: "https://github.com/docker/compose/releases/latest/download/docker-compose-linux-{{ remote_arch.stdout }}"
        dest: ~/.docker/cli-plugins/docker-compose
        mode: +x
      
- name: Add ec2-user to docker group
  hosts: docker_server
  become: yes
  tasks:
    - name: Add ec2-user to Docker group
      user: 
        name: ec2-user
        groups: docker
        append: yes
    - name: Reconnect to server session
      meta: reset_connection

- name: Test docker pull
  hosts: docker_server
  tasks:
    - name: Pull redis
      docker_image:
        name: redis
        source: pull

- name: Start Docker containers
  hosts: docker_server
  vars_files:
      - project-vars
  tasks:
    - name: Copy docker-compose
      copy:
        src:  <full-local-path-docker-compose-yaml-file>
        dest: /home/ec2-user/docker-compose.yaml
    - name: Docker Login
      docker_login: 
        username: docker-username
        password: "{{docker_password}}"
    - name: Start containers from compose
      community.docker.docker_compose_v2:
        project_src: /home/ec2-user
        state: present
        
